# Generated by Django 3.1.14 on 2022-12-19 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20221217_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(verbose_name='Время появления')),
                ('disappeared_at', models.DateTimeField(verbose_name='Время исчезновения')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('health', models.IntegerField(verbose_name='Здоровье')),
                ('strength', models.IntegerField(verbose_name='Атака')),
                ('defence', models.IntegerField(verbose_name='Защита')),
                ('stamina', models.IntegerField(verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon')),
            ],
        ),
    ]
