# Generated by Django 4.2.3 on 2023-08-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemon_description_alter_pokemon_defence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='title',
        ),
    ]
