# Generated by Django 3.1.14 on 2022-12-19 11:01

from django.db import migrations

def copy_entity(apps, schema_editor):
    NewPokemonEntity = apps.get_model('pokemon_entities', 'NewPokemonEntity')
    PokemonEntity = apps.get_model('pokemon_entities', 'PokemonEntity')
    for pokemon_entity in PokemonEntity.objects.all():
        NewPokemonEntity.objects.get_or_create(
            pokemon=pokemon_entity.pokemon,
            latitude=pokemon_entity.latitude,
            longitude=pokemon_entity.longitude,
            appeared_at=pokemon_entity.appeared_at,
            disappeared_at=pokemon_entity.disappeared_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_newpokemonentity'),
    ]

    operations = [
        migrations.RunPython(copy_entity),
    ]
