# Generated by Django 3.1.14 on 2022-12-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20221219_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PokemonEntity',
        ),
    ]
