# Generated by Django 3.1.14 on 2022-12-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_delete_pokemonentity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPokemonEntity',
            new_name='PokemonEntity',
        ),
    ]
