# Generated by Django 3.1.14 on 2023-01-06 19:43

from django.db import migrations


def copy_pokemon(apps, schema_editor):
    Pokemon = apps.get_model('pokemon_entities', 'Pokemon')
    NewPokemon = apps.get_model('pokemon_entities', 'NewPokemon')
    for pokemon in Pokemon.objects.all():
        NewPokemon.objects.get_or_create(
            title=pokemon.title,
            title_en=pokemon.title_en,
            title_jp=pokemon.title_jp,
            description=pokemon.description,
            image=pokemon.image,
            previous_evolution=pokemon.previous_evolution,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_newpokemon'),
    ]

    operations = [
        migrations.RunPython(copy_pokemon),
    ]
