# Generated by Django 3.1.14 on 2023-01-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20230106_2315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPokemon',
            new_name='Pokemon',
        ),
    ]
