# Generated by Django 3.1.14 on 2023-01-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0021_auto_20230107_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name': 'Тип покемона', 'verbose_name_plural': 'Типы покемонов'},
        ),
        migrations.AlterModelOptions(
            name='pokemonentity',
            options={'verbose_name': 'Покемон', 'verbose_name_plural': 'Покемоны'},
        ),
    ]
